# Generated by Django 3.1.3 on 2021-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210109_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
