# Generated by Django 3.1.3 on 2021-01-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
