# Generated by Django 3.2.4 on 2021-06-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210618_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
