# Generated by Django 3.2 on 2021-08-26 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_delete_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchedBy',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
